name: habittacker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#02d808"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg